### ISSUE TITLE
Improve StepProgress Granularity

### ISSUE THREAD

**Issue by cbravo** [russellgoldenberg/scrollama#104]
First off, This is an awesome library! Thank you to everyone that has worked on it. 

Currently we are struggling with one aspect of using Scrollama. We are using stepProgress to pass progress to a greensock animation timeline so we can scrub through an animation on scroll like so:

```
scroller
      .setup({
        step: myStepElement,
        offset: 0,
        progress: true,
        threshold: 1,
      })
      .onStepProgress(({ progress }) => {
        myGsapTimeline.progress(progress);
      });
```

however because this library is forcing progress to be reported as a 3 digit number (https://github.com/russellgoldenberg/scrollama/blob/master/src/init.js#L326) it forces our timeline animation to only have a maximum of 1000 keyframes which results in janky playback if our animation is being played over a stepElement that is taller than 1000 pixels of which we have several instances. 

would you consider a PR that allows control of how granular the progress value returned? Do you forsee any performance problems? e.g. does the number NEED to be rounded?

another workaround I was toying with in my head would be to stack a few 1000px stepElements  and inside the onStepProgress function derive a more precise progress by doing something like:
```
onStepProgress(({ index, progress }) => {
        const totalStepElements = 4
        const stepRatio = (1 / totalStepElements)
        const overallProgress = stepRatio * index + (stepRatio * progress)
        myGsapTimeline.progress(overallProgress);
      });
```

**Comment by russellgoldenberg** [comment]
The decimal places was an arbitrary decision. Removing that now in v2.1.6. Curious if your hack solution worked out for you though. Also be aware that the implementation of the granularity for intersectionObserver is not consistent across browsers so I wouldn't rely on  that for anything critical.

**Comment by cbravo** [comment]
We ended up just reverting to scrollmagic for the particular project we were using this on. I think it would have worked. We had our fingers crossed too that safari would catch up in terms of its implementation of intersection observer and the choppiness of the polyfill on that platform.
