### ISSUE TITLE
onStepProgress not firing correctly on iPhone

### ISSUE THREAD

**Issue by iDVB** [russellgoldenberg/scrollama#105]
Likely similar to https://github.com/russellgoldenberg/scrollama/issues/36

`onStepProgress` does not seem to fire correctly on iPhone (X / iOS `v13.1.3` )

**Reproduction Steps:**

- On iPhone Safari to: https://gwv56.csb.app/
- test scrolling to bottom of page then back up.

[Code here]: https://codesandbox.io/s/scrollama-gsap-test-gwv56

## Expected:
- Green square should rotate as you scroll into the green area.
- This animation should be aligned with scroll and should occur whether scrolling up or down.

## Actual:

**TEST 1:**
- notice that the debug line is not yet into the green area
- `scroll down`... 
- nothing happens at all. Even my console of `progress` does not happen

**TEST 2:**
- from the bottom of the page, `scroll up`...
- the animation now appears to work

**TEST 3:**
- Edit `line 18` https://codesandbox.io/s/scrollama-gsap-test-gwv56 changing to `offset: 0.1`
- notice how the debug line is now already in the green area.
- scroll down
- other then an initial jump (likely due to the browsers auto display of bottom bar) it now seems to work fine no issues.

**Comment by russellgoldenberg** [comment]
I just tested and was able to reproduce on the [progress demo](https://russellgoldenberg.github.io/scrollama/progress/) by setting offset to 0. However, it was using an old polyfill of intersection-observer (v0.5) and once I tried removing (not necessary for ios 13) and using the latest the progress event fired fine.

**Comment by akellbl4** [comment]
I have the same issue but it reproduces inconsistent on my page. Will try to create an example.

**Comment by CXHub** [comment]
Hi, 

I have the same issues on IOS. Did anyone found a solution yet?

@russellgoldenberg

**Comment by mtdmali** [comment]
FWIW I was having similar issues using Scrollama v2.2.3, where both `onStepEnter` and `onStepProgress` events were not firing as expected on my iPhone 12 using iOS 15.1.1.

Simply updating Scrollama to the latest v3.0.2 seems to have solved the problem, all the events are firing like normal for me now in both Chrome & Safari!

@russellgoldenberg

**Comment by CXHub** [comment]
@mtdmali Thanks for the update!
