### ISSUE TITLE
How can I have 'sticky' on left and 'scrolling' on right

### ISSUE THREAD

**Issue by rraadd88** [russellgoldenberg/scrollama#109]
Hi developer,
I wonder if there is an easy way to change the sides of 'scrolling' and 'sticky' element in the "sticky-side" layout (https://russellgoldenberg.github.io/scrollama/sticky-side/).

**Comment by russellgoldenberg** [comment]
you can re-order the dom elements, so put the `figure` before the `article` tag and it will swap them!
