### ISSUE TITLE
Back to start on load

### ISSUE THREAD

**Issue by BMPMS** [russellgoldenberg/scrollama#118]
Hi there, 

A really stupid question but I can't work out how to reset the scroller so that it is back at step 1 on load.

window.addEventListener("load", ???);

I've tried re-running init() and window.scrollTo, resetting window.scrollY.

Any advice greatly appreciated.

**Comment by ouw-devs** [comment]
> 
> 
> Hi there,
> 
> A really stupid question but I can't work out how to reset the scroller so that it is back at step 1 on load.
> 
> window.addEventListener("load", ???);
> 
> I've tried re-running init() and window.scrollTo, resetting window.scrollY.
> 
> Any advice greatly appreciated.

scrollama.destroy() and re-running scrollama.setup() should handle it
