### ISSUE TITLE
Update offset on resize? [Potential bug]

### ISSUE THREAD

**Issue by ogelin** [russellgoldenberg/scrollama#119]
When calling scroller.resize(), there should be a way to update the offset. 

```
const scroller = scrollama()

function init () {
  scroller
    .setup({
      step: '#...,
      offset: midpoint + 'px',
      debug: true
    })
    .onStepEnter(...)

  window.addEventListener('resize', handleResize)

}

function handleResize () {
  scroller
    .setup({
      step: '...',
      offset: newMidpoint + 'px',
      debug: true
    })
    .onStepEnter(e => handleStepEnter(e, callbacks))

  scroller.resize()
}
```

This results in many offsets seemingly being set : 

![image](https://user-images.githubusercontent.com/16294757/104960241-d26e9000-59a1-11eb-809e-4ef3144c070b.png)

A potential solution could be to pass the new offset as param to the .resize() function.

**Comment by russellgoldenberg** [comment]
There is a [method](https://github.com/russellgoldenberg/scrollama#scrollamaoffsettriggernumber-or-string) for this, so you could chain them together or call one after the other. Assuming that is what you are looking for?

**Comment by ogelin** [comment]
Yes, wonderful, sorry about that & thanks for the great lib.
