### ISSUE TITLE
working with a scrollable parent

### ISSUE THREAD

**Issue by mathisonian** [russellgoldenberg/scrollama#122]
Hi @russellgoldenberg,

This library is really great, thanks for making it and the extensive docs. I'm running into a scenario where I'm hitting the error `scrollama error: step elements cannot be children of a scrollable element. Remove any css on the parent element with overflow: scroll; or overflow: auto; on elements with fixed height`. 

I'm wondering how big of an issue this is, and if is surmountable with some work? I could contribute a PR if you provide some direction.

For what its worth the situation I'm in is an app with main container that has its height set to `100vh` and then allows content to scroll inside of that. It is done this way to allow there to be a left sidebar that stays fixed in place via css grid. Scrollama already mostly works in this case, it just _doesn't work when scrolling in reverse_. To me this makes it seem like maybe?? there is a straightforward patch to fix the reverse direction.

**Comment by russellgoldenberg** [comment]
Hey! So that was a feature added via [PR 106](https://github.com/russellgoldenberg/scrollama/pull/106) that I actually didn't write. Here is the initial [PR 101](https://github.com/russellgoldenberg/scrollama/pull/106) with more details too. I think he discovered some bugs if the parent was scrollable with our calculations, but you could try disabling the error checking to see if it works for you. In which case, we could consider an override or something maybe?

**Comment by russellgoldenberg** [comment]
@mathisonian i've been experimenting with a big rewrite, would you want to test it out and see if it solves your issue?

**Comment by mathisonian** [comment]
Thanks @russellgoldenberg! I'd be happy to test it out and see if that fixes things. If not I can start digging into the PRs you linked above and see what a reasonable workaround would be

**Comment by russellgoldenberg** [comment]
Give [this](https://raw.githubusercontent.com/russellgoldenberg/scrollama/v3/build/scrollama.js) a go. Literally developing it as we speak, so it may yield other errors.

**Comment by mathisonian** [comment]
Hey, it works! Magic ✨

**Comment by mathisonian** [comment]
There don't appear to be any other immediate errors, but I'll test it a little more extensively

**Comment by russellgoldenberg** [comment]
oh sweet. something that won't work: firing previous enter/exits if you anchor-link jump passed them.
also two new things worth testing (if relevant): auto resize handled using resize observer (so no more manually calling a resize event on the scroll instance), per-element offset trigger (using data-offset attribute) for custom tweaks.

**Comment by mathisonian** [comment]
Ah okay good to know - i'll test those out and report back soon

**Comment by mathisonian** [comment]
So far so good. Things seem to be working smoothly after removing the resize function call. I haven't tested the per-element offsets yet

**Comment by albertkun** [comment]
Just wanted to say a big thank you for adding this feature @russellgoldenberg  and thank you @mathisonian for mentioning this!! i'm using scrollama for a storymap with leaflet.js and it works great!!

**Comment by russellgoldenberg** [comment]
hopefully in the next month or so if I can score some free time
