### ISSUE TITLE
Snap to view during scrolling

### ISSUE THREAD

**Issue by Mozartuss** [russellgoldenberg/scrollama#129]
Is there a way to snap into a view during scrolling, maybe with the css module [CSS Scroll Snap Module](https://www.w3.org/TR/css-scroll-snap-1/) or with a js lib like [scroll-snap](https://github.com/lucafalasco/scroll-snap)?

**Comment by russellgoldenberg** [comment]
seems like you could just incorporate those and scrollama would still work just fine?
