### ISSUE TITLE
Direction in onStepEnter undefined when overflow set on parent

### ISSUE THREAD

**Issue by ivanbacher** [russellgoldenberg/scrollama#134]
I have the following css styles applied to my main page container:

```
. parent {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    overflow: auto;
}
```

`response.direction` undefined in the onStepEnter and onStepExit callbacks.

Looking at [scroll.js](https://github.com/russellgoldenberg/scrollama/blob/main/src/scroll.js), it uses `window.pageYOffset`.

What do you think about adding in the option on `.setup` to pass in a container element, then use `.scrollTop` on that element for the calculation? If no element is passed, then window.pageYOffset could be used by default.

```

```

**Comment by russellgoldenberg** [comment]
thanks for the PR. just tweaked a little to simplify code. should be available in the latest release`3.1.0`
