### ISSUE TITLE
Stickyfill not used?

### ISSUE THREAD

**Issue by vdavez** [russellgoldenberg/scrollama#140]
The "sticky" [examples](https://russellgoldenberg.github.io/scrollama/sticky-side/) still refer to the `Stickyfill` even though they're not currently used. [Source](https://github.com/russellgoldenberg/scrollama/blob/5bdd8f197c28577a3b812161a24649effb52946d/docs/sticky-side/index.html#L182-L185)

It didn't turn up an error because there aren't any elements with the `sticky` class to be set up using `setupStickyfill`. 

I'm not sure whether you still plan to use stickyfill or not, but thought I'd flag that the code as it's written currently appears to be unnecessary.

**Comment by russellgoldenberg** [comment]
thanks for spotting, removed!
