### ISSUE TITLE
Response Object and undefined Direction Property issue?

### ISSUE THREAD

**Issue by firecall** [russellgoldenberg/scrollama#142]
Hi, 

I'm inspecting the 'response' object and finding that 'direction' is undefined. 

Am I doing something wrong, or is this a bug?

```
element: [object HTMLDivElement]
index: 0
direction: undefined
```

Example code:

```
scroller
  .setup({
    step: '.vh-cb',
    root: $root,
    debug: false,
    offset: '326px',
    container: $container,
    progress: true
  })
  .onStepEnter((response) => {
    for (const prop in response) {
      if (response.hasOwnProperty(prop)) {
        console.log(`${prop}: ${response[prop]}`)
      }
    }
    // additional code
  })
  .onStepExit((response) => {
     // additional code
  })
```

Thanks for making this by the way! :-)

**Comment by firecall** [comment]
More testing shows that it's not liking overflow: scroll!

**Comment by Joontae93** [comment]
I actually have the same issue...and I don't have a root element defined. Thoughts?

**Comment by firecall** [comment]
> I actually have the same issue...and I don't have a root element defined. Thoughts?

In the end I implemented my own solution using native APIs. 

It wasn't too hard, and I got exactly what I wanted :-)

Scrollama is great, it just wasn't working exactly for my use case!

**Comment by Joontae93** [comment]
> It wasn't too hard, and I got exactly what I wanted :-)

So you're saying I should work a little harder to be a better developer?? Ughhhhhhhhhh. 

I see your raise, and I call.

**Comment by Joontae93** [comment]
Found my solution: don't declare a container.
