### ISSUE TITLE
position sticky demo?

### ISSUE THREAD

**Issue by 1wheel** [russellgoldenberg/scrollama#17]
I think it could make most of positioning css obsolute

https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning

**Comment by russellgoldenberg** [comment]
Is there a reliable polyfill?

**Comment by 1wheel** [comment]
Looks like there is: https://github.com/wilddeer/stickyfill

**Comment by russellgoldenberg** [comment]
Ooh neat - I'll check out.

**Comment by russellgoldenberg** [comment]
* [v1](https://russellgoldenberg.github.io/scrollama/sticky-css/)
* [v2](https://russellgoldenberg.github.io/scrollama/sticky-js/)
