### ISSUE TITLE
Basic and Progress examples break on resize

### ISSUE THREAD

**Issue by colinmorris** [russellgoldenberg/scrollama#22]
Vertically resizing the browser window or just opening the developer console breaks these examples. The [progress](https://russellgoldenberg.github.io/scrollama/progress/) steps will end at some progress < 100%, and the elements in the [basic](https://russellgoldenberg.github.io/scrollama/basic/) example will get triggered at the wrong time.

**Comment by russellgoldenberg** [comment]
I didn't put in any resize events to handle responsive on either of these demos. However, it is a two-liner (simply setting up a resize event handler and calling the scrollama resize function) - so I'll add it in.
