### ISSUE TITLE
screencasts of start to finish implementation

### ISSUE THREAD

**Issue by russellgoldenberg** [russellgoldenberg/scrollama#23]
* [x] 0: step triggers event on static graphic, responsive on mobile - [example](https://www.nytimes.com/interactive/2017/05/18/climate/antarctica-ice-melt-climate-change-science.html)
* [ ] 1: fixed graphic with step triggers, responsive on mobile - [example](https://www.nytimes.com/interactive/2017/05/31/climate/trump-climate-paris-agreement.html)
* [ ] 2: fixed graphic with step triggers, stacked on mobile - [example](http://www.nytimes.com/newsgraphics/2013/10/27/south-china-sea/)
* [ ] 3: fixed graphic with progress based triggers, responsive on mobile - [example](https://www.nytimes.com/interactive/2015/01/09/sports/the-dawn-wall-el-capitan.html)
* [ ] 4: sticky graphic pattern with step triggers, responsive on mobile - [example](http://www.abc.net.au/news/2017-10-16/north-korea-missile-range-map/8880894)

**Comment by iamdubx** [comment]
Oh my, can't wait to see it! Will there be an announce?

**Comment by russellgoldenberg** [comment]
Excellent. Putting the first one or two together this weekend. I'll probably just tweet it out (@codenberg) / add it to the README.

**Comment by bovas85** [comment]
Those sites are so cool, I really like this approach and how easy it is to setup

**Comment by twang91** [comment]
0: step triggers event on static graphic - https://www.youtube.com/watch?v=rXHtHLiBWhY
Is there any plan to continue these screencasts? Particularly for implementing interactive elements or d3 charts?

**Comment by monizjp** [comment]
Thank you for making this video.  Hope to see more in the future
