### ISSUE TITLE
Wrong license in file

### ISSUE THREAD

**Issue by LucaRosaldi** [russellgoldenberg/scrollama#29]
Just a trifle, still: in the Readme the license is MIT, while in the file is Apache v2.

**Comment by martgnz** [comment]
Are you sure [this is Apache v2](https://github.com/russellgoldenberg/scrollama/blob/master/LICENSE)?

**Comment by russellgoldenberg** [comment]
Bit confused, the README.md license and LICENSE file are both the same (and I thought MIT). Not too familiar with licenses so maybe I'm missing something. I just did what I've seen by other authors I follow. Open to suggestions!

**Comment by LucaRosaldi** [comment]
Sorry, I meant the license in the build file.

![schermata 2017-11-24 alle 08 05 47](https://user-images.githubusercontent.com/1115658/33198962-696c35d8-d0ee-11e7-9c55-a58cc956d4d7.jpg)


I see that’s been fixed in the [latest commit](https://github.com/russellgoldenberg/scrollama/commit/1072902a63eb1f0f579b312620b9f32db709e2d6).
