### ISSUE TITLE
doesn't trigger on first load if past

### ISSUE THREAD

**Issue by russellgoldenberg** [russellgoldenberg/scrollama#33]
`direction` should be null by default, and the direction check should be a `not` check, not equals.

**Comment by LucaRosaldi** [comment]
Yes. When DOM has loaded, elements which are currently in viewport and elements already scrolled past should be treated as entered steps.

When used for a "fade in on scroll" effect, the elements which stand above the trigger line do not appear at all :(

Waiting to see this fixed.
