### ISSUE TITLE
Breaks when used with Angular CLI on Safari

### ISSUE THREAD

**Issue by shampliu** [russellgoldenberg/scrollama#35]
Developing a project using Angular 4 and we included the Scrollama initialization in the `NgAfterViewInit` lifecycle hook but the `setup` function is breaking the site in Safari.

Specifically, it's the lines:

```
var obs = new IntersectionObserver(intersectStepProgress, options);
obs.observe(el);
```

We believe some polyfills are being overwritten by the Angular CLI tool and so the IntersectionObserver doesn't work properly in Safari. 

We tested the demo code from [this tutorial](https://pudding.cool/process/introducing-scrollama/) in Angular and it breaks it.

**Comment by russellgoldenberg** [comment]
Interesting. I have never used Angular so I will be no help finding the issue here. It sounds like it might be something to fix with how Angular integrates the library rather than scrollama itself? Totally open to suggestions to resolve this / PRs.

**Comment by bretmorris** [comment]
My guess is that it has something to do with the polyfill since it works fine in Chrome (which supports Intersection Observer). It might have to do with the order of operations. I think Angular CLI loads a bunch of polyfills upfront. Is it possible that one of those libraries is conflicting with the polyfill that comes with scrollama? Is there any way to load scrollama w/o the polyfill and manually include the polyfill separately?

Sort of a shot in the dark.

**Comment by bretmorris** [comment]
After some further testing, I think I have a slightly better idea of what's going on. It's not related to the order of operations. Removing the polyfill from this lib and manually using one doesn't solve the prob. 

The error has something to do with with the intersection observer polyfill and Angular. Seems related to the `root`. Might have something to do with how Angular is injecting HTML into the DOM.

**Comment by bretmorris** [comment]
@russellgoldenberg it's related to this issue https://github.com/w3c/IntersectionObserver/issues/272. It doesn't look like the polyfill has published the latest version, which includes an option that fixes Safari.

**Comment by russellgoldenberg** [comment]
Looks like the polyfill was updated I am using the latest version. Is this resolved?

**Comment by bretmorris** [comment]
I think so @russellgoldenberg

**Comment by russellgoldenberg** [comment]
The polyfill has been removed from the build in the latest release. This should hopefully help any polyfill issues with Angular.
