### ISSUE TITLE
Multiple containers on the same page?

### ISSUE THREAD

**Issue by GitNoise** [russellgoldenberg/scrollama#37]
Is it possible to have multiple containers on the same page? 

I cannot see how one should initialize multiple scrollers with multiple listeners.

**Comment by russellgoldenberg** [comment]
You should be able to simply create multiple instances... eg:

```javascript
// instantiate the scrollama
const scroller1 = scrollama();
const scroller2 = scrollama();

// setup the instance
scroller1
  .setup({
    step: '.container-1 .step'
  })

scroller2
  .setup({
    step: '.container-2 .step'
  })
```

**Comment by bclinkinbeard** [comment]
This is how I've gotten multiple containers running so far. https://codepen.io/bclinkinbeard/pen/JOgdwq?editors=1000

Note you'll have to use [the debug view](https://s.codepen.io/bclinkinbeard/debug/JOgdwq) for it to behave correctly, per #38 

I just stuck everything inside the `init` function to avoid the globals created in the demos. If there's a better way I'm all ears. :)

**Comment by GitNoise** [comment]
@bclinkinbeard 
I implemented a similar solution as yours but as in your example I get the same "error"... onStepEnter is triggered for both scrollers when one of their steps is triggered.

You can see this if you have scroll to the end of the first scroll container and observe the value in the second scroll container without entering it.

**Comment by GitNoise** [comment]
Is this a bug or a feature :)

**Comment by GitNoise** [comment]
As long as the containers aren't next to each other it seems to work fine.
