### ISSUE TITLE
Issues running in CodePen

### ISSUE THREAD

**Issue by bclinkinbeard** [russellgoldenberg/scrollama#38]
Hello, I converted the demo from the announcement post to a CodePen, and it has some issues running in the editor. If you open the debug view so it's not inside an iframe it works as expected.

Just FYI.

https://codepen.io/bclinkinbeard/pen/OOKXjz

**Comment by ugrupp** [comment]
Same issue here,`response.progress` in the progress callback gives wild results.
Debug mode fixes it.

https://codepen.io/21sieben/pen/mXZJZJ

**Comment by smnarnold** [comment]
Not sure why this ticket was closed. It still happening in CodePen.
The example provided ([https://codepen.io/bclinkinbeard/pen/OOKXjz](https://codepen.io/bclinkinbeard/pen/OOKXjz)) still doesn't react as expected.

**Comment by smnarnold** [comment]
Anyone has a lead?
