### ISSUE TITLE
Intersection Observer Polyfill?

### ISSUE THREAD

**Issue by cferdinandi** [russellgoldenberg/scrollama#41]
Hi there! This is awesome!

Given the spotty browser support for Intersection Observer, I might recommend include a version with [the polyfill](https://github.com/w3c/IntersectionObserver/blob/master/polyfill/intersection-observer.js) baked in, or mentioning it in the docs and pointing people to it.

Would be nice to get some browser support info in the readme, too.

**If you want my help in any way with this, please just let me know and I'll fork and PR.**

**Comment by russellgoldenberg** [comment]
Thanks! I actually have the poyfill [included](https://github.com/russellgoldenberg/scrollama/blob/master/index.js#L1) by default, I will make an issue to include it in the readme. I still haven't gotten around to browser support testing yet, there is an [open issue](https://github.com/russellgoldenberg/scrollama/issues/9).

**Comment by russellgoldenberg** [comment]
BTW I'll always take the help with a PR if you want to tackle anything.

**Comment by cferdinandi** [comment]
Oh man, so sorry! I dug quickly through the code and missed that entirely. Thanks!
