### ISSUE TITLE
How to destroy an instance?

### ISSUE THREAD

**Issue by codeofsumit** [russellgoldenberg/scrollama#46]
With HMR, a component is loaded twice and if that component includes scrollama, it'll be initiated twice.
How can I destroy an instance (so all events are cleaned up and everything)?
Looking for something like
```
scroller.destroy();
```

**Comment by russellgoldenberg** [comment]
Should be easy enough - I'll open a new issue

**Comment by codeofsumit** [comment]
alright this can be closed then in favor of #47
