### ISSUE TITLE
destroy method to remove all observation and disable

### ISSUE THREAD

**Issue by russellgoldenberg** [russellgoldenberg/scrollama#47]

**Comment by theamnesic** [comment]
Hi!

`scrollama.destroy()` seems not to work anymore, `undefined`.
On the other hand `scrollama.disable()` and `scrollama.enable()` both work : 

![image](https://user-images.githubusercontent.com/242203/36421552-2b3a6920-1639-11e8-92c8-d86ed3c0d386.png)

Any idea?

— G

**Comment by russellgoldenberg** [comment]
There is no return value on the function, so undefined is the correct return. 

It should have removed all intersectionObserver listeners and not trigger any of the callback functions to update. Is that not happening?

**Comment by theamnesic** [comment]
No, it doesn't remove my observers...

Using a basic setup and everything works like a charm, only this destroy method doesn't work.

**Comment by russellgoldenberg** [comment]
Ah so the callbacks are still firing? What browser/version are you using?

**Comment by theamnesic** [comment]
Sorry, my mistake, `scrollama.destroy()` works!
I was fooled by the visual debugging tool which did not disappear when destroying (using PJAX) : 

![image](https://user-images.githubusercontent.com/242203/36427901-b066a5f4-164e-11e8-8a3d-22abfe6ef7b9.png)

Maybe this one should be remove/reset too.

Thanks for your help!
