### ISSUE TITLE
cannot read property state of undefined

### ISSUE THREAD

**Issue by codeofsumit** [russellgoldenberg/scrollama#48]
Hi there,

this code:

```
const scroller3 = scrollama();

scroller3
  .setup({
    step: 'section',
    offset: 0.05,
    progress: true,
    debug: false,
  })
  .onStepProgress(({ element }) => {
    if (element.classList.contains('is-white')) {
      this.isDark = false;
    } else {
      this.isDark = true;
    }
  });
```

causes a lot of these errors on my page:

![image](https://user-images.githubusercontent.com/2399810/34918846-2415e49a-f95a-11e7-8341-abe29f822311.png)

Might have something todo with no `section` element being available on the page? I'm not sure though - any advice?

**Comment by russellgoldenberg** [comment]
If there is no `section` element then there are no steps, so scrollama won't work. I just pushed a change that will return an error if the `step` elements don't exist which should help your issue.
