### ISSUE TITLE
Scroll bound animation?

### ISSUE THREAD

**Issue by med4891** [russellgoldenberg/scrollama#55]
Hi! Been playing around with scrollama and couldn't figure out if its possible to do a scroll bound animation with greensock?

I've managed to get it to work with the 'onStepEnter/onStepExit' but that plays the animation immediately. Also with this scenario, if i were to scroll up and down a couple of times, the animation will continue to replay the number of times it was scrolled.

Here's my codepen:
[link](https://codepen.io/anon/pen/WMrraP)

Not entirely sure if this is the best implementation of gsap with scrollama. Any insight will be much appreciated! Thank you

**Comment by russellgoldenberg** [comment]
Not sure what you are going for, when the step enters, the animation fires, which seems to be the desired effect? Unless do you mean "scroll bound" to equate to a fraction of the full animation on each scroll? In that case, check out the `progress` option. Also if you want to disable to after it fires, use the `once` option.

**Comment by med4891** [comment]
>  Unless do you mean "scroll bound" to equate to a fraction of the full animation on each scroll?

Yep, that was what i was trying to achieve but i could not really figure out how to. Will relook into the `progress` option again. Thanks for the reply

**Comment by martgnz** [comment]
Apart from setting `progress` to true you need to call your code from `onStepProgress` instead of `onStepEnter` or `onStepExit`.

[Reference](https://github.com/russellgoldenberg/scrollama#scrollamaonstepprogresscallback).
