### ISSUE TITLE
Manage Viewport Jumps

### ISSUE THREAD

**Issue by digitaltopo** [russellgoldenberg/scrollama#56]
Is there a way to manage viewport jumps that were implemented by #30 ?

Take this scenario for example: If you load the page at step 5 (scrolled half way down a page), step 5's `onStepEnter` get's triggered, but then so do all of the other steps above. These don't fire in order, so we get step 5, then 4, 3, 2, 1. In my case, I have effects in step 5 that is undone by previous steps.

Some possible solutions:

- Could we make a current step indicator available? You could use this in some of the logic that fires during the onStepEnter callback.
- Could we apply these steps in order? Although then you'd be running through the whole app each time you reload it.
- Can we have the ability to turn off "backfilling" the steps?

If there is already a way around this and I've missed it, could you please let me know? 

Would love to hear your thoughts. Thanks!

**Comment by russellgoldenberg** [comment]
Are you using the latest version? Your second solution (apply these steps in order) should be the case now per a recent code update.

**Comment by SantoFejoDK** [comment]
same issue here.. onStepEnter gets fired in random orders with version 1.4.3.
I've added a console.log(index) to onStepEnter and when I have scrolled down to the middle of the page, hit refresh, the numbers appear seemingly random, even in reverse sometimes.

**Comment by cauyeung** [comment]
I was able to workaround this issue by keeping an associative array updated as to which steps have entered but not exited yet. The step that hasn't yet exited is then the active step.

var activeStepByIndex = {}

var checkActive = () => {
  for(var key in activeStepByIndex) {
    if(activeStepByIndex[key] == true) {
      console.log('index ' + key + ' is active');
      break;
    }
  }
}

scrollama.setup({...})
  .onStepExit(({index}) => {
    activeStepByIndex[index] = false;
    checkActive();
  })
  .onStepEnter(({index}) => {
    activeStepByIndex[index] = true;
    checkActive();
  });

**Comment by nicooprat** [comment]
Need that feature too :) I'd like not to trigger previous steps on init when reloading the page if already scrolled halfway down.
