### ISSUE TITLE
IntersectionObserver polyfill causes errors with server-side rendering

### ISSUE THREAD

**Issue by simon360** [russellgoldenberg/scrollama#57]
Our project does server-side rendering, so when we import `scrollama`, we get errors about `window` being undefined. That's because the `IntersectionObserver` polyfill isn't meant to run on the server.

A lot of other projects have polyfills as a prerequisite, rather than having them as dependencies. This gives developers the option to exclude the polyfill if their browser support list doesn't require it (which will, eventually, happen with `IntersectionObserver`), or when not running in a browser environment (such as for SSR).

**Comment by russellgoldenberg** [comment]
It is a valid point, one that I also believe would fix #35.  My initial hesitation is that as it stands, there is not great browser support yet, so I wouldn't want people implementing it to scratch their heads if they didn't read the directions properly... But clear usage instructions *should* solve that, so I'll probably go ahead and separate them. Thanks!

**Comment by russellgoldenberg** [comment]
Polyfill removed from build in latest release.

**Comment by simon360** [comment]
Thanks for the quick resolution here @russellgoldenberg - confirmed it's working well for us now!
