### ISSUE TITLE
Problem with Resize event

### ISSUE THREAD

**Issue by woowski** [russellgoldenberg/scrollama#62]
Hi @russellgoldenberg 

Thanks a lot for that great piece of code.

I've encountered an issue trying to setup a resize function. I've tried to throttle the resize event, or debounce it like i've did there : [scrollama-problem-resize](https://test-scrollama-resize.netlify.com)

The problem is that, on some resize events, two steps elements become active when only one is supposed to get the class="is-active" attached to it. Reload the page or scrolling to the next step solve the issue, so there might be a problem there during the resize event and the scroller.resize(); 

Any advice on how to implement a good resize function with scrollama to avoid that issue ?

I'm trying to understand on how to deal with it for the last couple of days and it's driving me mad. Everything is working fine, except for those double active steps ...

js: 

```
//DEBOUNCE
function debounce(func, wait, immediate) {
	var timeout;
	return function() {
		var context = this, args = arguments;
		var later = function() {
			timeout = null;
			if (!immediate) func.apply(context, args);
		};
		var callNow = immediate && !timeout;
		clearTimeout(timeout);
		timeout = setTimeout(later, wait);
		if (callNow) func.apply(context, args);
	};
};


var container = document.querySelector('#scroll');
var text = container.querySelector('.scroll__text');
var steps = text.querySelectorAll('.step');

// load
var scroller = scrollama();

// call on resize
function handleResize(){
  scroller.resize();
}
// Resize event
// --> y or n
function size() {
    if(window.matchMedia("(min-width:769px)").matches) {
        handleResize();
        scroller.enable();
    } else {
        handleResize();
        scroller.disable();
    };
  };

// --> call on resize
var debounce_resize = debounce(function() {
  size();
}, 250);

// event enter
function handleStepEnter(response) {
  response.element.classList.add('is-active');
  console.log('is-enter');
}

// event exit
function handleStepExit(response) {
  response.element.classList.remove('is-active');
  console.log('is-out');
}

// init
// --> call on DOMloaded
function init() {

  // --> 
  size();

  scroller.setup({
    step: '.scroll__text .step',
    debug: true,
  })
    .onStepEnter(handleStepEnter)
    .onStepExit(handleStepExit);

  // setup resize event
  window.addEventListener('resize', debounce_resize);
}

// GO
document.addEventListener("DOMContentLoaded", function(event) {
    init();
  });
```
Let me know,

Many thanks !

**Comment by russellgoldenberg** [comment]
I just tested out resizing and it seems to be working as intended. I'm in latest Chrome. What browser/version are you on?
