### ISSUE TITLE
ReferenceError: Stickyfill is not defined

### ISSUE THREAD

**Issue by blehman** [russellgoldenberg/scrollama#63]
What is the library that contains the requirement for the [line of code using Stickyfill](https://github.com/russellgoldenberg/scrollama/blob/master/docs/sticky-js/index.html#L237)?

**Comment by russellgoldenberg** [comment]
https://github.com/russellgoldenberg/scrollama/blob/master/docs/sticky-js/index.html#L176

**Comment by anglilian** [comment]
Revisiting this issue because the links in the discussion are not longer usable. Not sure where I should import the stickyfill.min.js file from.

`Uncaught ReferenceError: Stickyfill is not defined
`
