### ISSUE TITLE
Misfired events on Chrome when window is zoomed

### ISSUE THREAD

**Issue by bmschmidt** [russellgoldenberg/scrollama#64]
On the latest Google Chrome (OS X Version 66.0.3359.117 (Official Build) (64-bit)), behavior seems to be incorrect when the window zoom level (i.e., the thing you change by pressing control-plus on the keyboard) is not 100%. At 125% zoom, eg., when the scrollpoint is halfway in between the two elements in the progress demo, both are firing (screenshot below); element 1 is counting down from 100% even though it should have exited, and element 2 has already started counting up. Firefox and Safari behave as expected.

![screen shot 2018-04-24 at 12 16 49 pm](https://user-images.githubusercontent.com/1110758/39200797-28284096-47bb-11e8-9935-6595cf3feab2.png)

The problem also shows up with Linux Chrome on a high resolution screen dell xps15; there I have to manually set the browser zoom to 50% to get it to fire at the right place because, I guess, something internally is adjusting the resolution from HD?

Thanks for your work.

**Comment by russellgoldenberg** [comment]
Good question - I haven't actually tested with different zoom levels. I will take a look and see if I can shed some more light.

**Comment by russellgoldenberg** [comment]
This is definitely an issue on zoom level. I would have to resize the detection areas based on the zoom level, which according to my googling is not an easy cross-browser thing.

**Comment by atav32** [comment]
Well, ran into this bug too. @russellgoldenberg any suggestions on where I should start looking to patch in a fix? I would normally start by checking out the unit tests, but uh... 😆

**Comment by pldg** [comment]
Same problem here.

```html
<div class="container">
  <div class="full-screen center-text sticky">
    <h1>Test</h1>
  </div>
</div>
```

```css
.container {
  height: 150vh
}

.full-screen {
  width: 100%;
  height: 100vh;
}

.center-text {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.sticky {
  position: sticky;
  top: 0;
}
```

```js
window.addEventListener('load', () => {
  const scroller = scrollama();

  scroller
    .setup({
      step: '.container',
      offset: 1,
      progress: true,
      threshold: 50
    })
    .onStepProgress(res => {
      console.log(res.progress);
    });
});
```

When I scroll down reaching the end of container:

- If window zoom is 100%, works fine on both Chrome and Firefox
- If window is zoomed, works fine on Firefox
- If window is zoomed, doesn't work on Chrome: `res.progess` never reach `1`

Chrome zoomed 150%:

![image](https://user-images.githubusercontent.com/24630716/62641913-ec025000-b944-11e9-8308-05650dc93809.png)

Firefox zoomed 150%:

![image](https://user-images.githubusercontent.com/24630716/62641950-fae90280-b944-11e9-9ad1-1d1cb6a5862a.png)

Any news on the fix? @russellgoldenberg
