### ISSUE TITLE
onStepProgress - Janky callbacks

### ISSUE THREAD

**Issue by RubenKos** [russellgoldenberg/scrollama#67]
Hi Russel,

First of all, thank you for your work on this library. It is great to use and very flexible.

After building a simple prototype, I noticed that onStepProgress unfortunately becomes very janky on Safari (and iOS). If you would look at the demo given on https://russellgoldenberg.github.io/scrollama/progress/ , you will notice that it will use much larger incremental steps than on Chrome or Firefox. I have tried playing around with the threshold option but this doesn't seem to impact this much.

At first I thought I was doing something wrong but as it is also available in your demo is most likely a bug. I was hoping that the library would function the same cross-browser.

Thank you in advance for any help.

**Comment by russellgoldenberg** [comment]
Yep, looks like the frequency of callback is far fewer in iOS and macOS. They both rely on the polyfill, so it is likely due to that. So I'm not sure there is a bug technically (at least not in scrollama), but a limitation to the polyfill's ability to produce the same results for this feature cross-browser. I'll do some more testing though, and make a note of it in the documentation.

**Comment by RubenKos** [comment]
After doing some extra research in the mean time I did get to the same conclusion that it must be the Polyfill not giving the same results unfortunately.

Would you be able to share which functions from the IntersectionObserver API you are using to create the progress callbacks? I can then create an issue on the IntersectionObserver repo to see if they can fix this in the Polyfill right here; https://github.com/w3c/IntersectionObserver/tree/master/polyfill

Thank you in advance and for your help so far. I really want to fix this so I can use this API in my current work instead of relying on performance heavy alternatives.

**Comment by russellgoldenberg** [comment]
Yup you want the `threshold` property.

[Here is the scrollama code](https://github.com/russellgoldenberg/scrollama/blob/master/src/init.js#L486)
[Here is property in Moz Docs with another example](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Thresholds)
