### ISSUE TITLE
add safari progress disclaimer to docs

### ISSUE THREAD

**Issue by russellgoldenberg** [russellgoldenberg/scrollama#68]

**Comment by steveooo9** [comment]
@russellgoldenberg Yeah! What's the status for this and is there a fix?
Because we had to disable some logic just for Webkit because of this..

**Comment by jhadenfeldt** [comment]
The IntersectionObserver implementation has finally been picked up after nearly no progress for 2 years, there are still some failing tests though: https://bugs.webkit.org/show_bug.cgi?id=159475

It doesn't look there is an ETA yet.
