### ISSUE TITLE
anything wrong in making multiple instances?

### ISSUE THREAD

**Issue by stratboy** [russellgoldenberg/scrollama#72]
hi! I'd like to use scrollama to both activate things on elements and to control main menu changes upon scroll. This would imply using different offset options for the document itself and for the other objects. So I guess, I should use more than one scrollama instance. Is it bad practice?

**Comment by allan-walker** [comment]
Have a look at this, does it answer your question? https://github.com/russellgoldenberg/scrollama/issues/37
