### ISSUE TITLE
Scrollama not working on Windows Surface

### ISSUE THREAD

**Issue by Ricozor** [russellgoldenberg/scrollama#73]
Windows surface is at the same time a tablette and a desktop.
In this specific case Scrollama doesn't work properly on Edge and Chrome (Firefox looks OK - except when  the event is triggered at the end of the scroll)

I think that the problem should be the same on similar device (Tablet Yoga...)

**Comment by jhadenfeldt** [comment]
I'm having no issues on a Surface Pro 4 with Edge 17, Chrome 69 or Firefox 63 when testing here: https://russellgoldenberg.github.io/scrollama/basic/

**Comment by nthitz** [comment]
I have the same issue as @chriszrc on a Google Pixelbook

**Comment by jonnyscholes** [comment]
Hmm I'm seeing pretty erratic behaviour on all the demos on my Windows machine using Chrome (cheap ACER laptop, Chrome 76). Works as smooth as butter on MacOS using same version of Chrome.

**Comment by chriszrc** [comment]
@russellgoldenberg any ideas what's going on with Windows here and even just the official demo?

**Comment by chriszrc** [comment]
@russellgoldenberg any updates here?

**Comment by chriszrc** [comment]
Huh, well, Happy Holidays, looks like the latest version of Chrome on Windows (79) no longer as this problem, huzzah!

![ezgif-7-4d6faa768e46](https://user-images.githubusercontent.com/25695785/70944310-d30b5900-2020-11ea-94bf-f2dc4a21819a.gif)
