### ISSUE TITLE
Offset array 

### ISSUE THREAD

**Issue by bovas85** [russellgoldenberg/scrollama#76]
Intersection Observer allows setting different offsets for each entry using an array. 

Is this possible and if not would this be a good feature for enhancement?

**Comment by russellgoldenberg** [comment]
Yeah i didn't include that since it would just add complexity, but I understand the use case. It would have to require using data attributes on the dom elements to pass the offset parameter. Open to checking out a PR though.

**Comment by russellgoldenberg** [comment]
added in [3.0](https://github.com/russellgoldenberg/scrollama/tree/v3)
