### ISSUE TITLE
Event not always firing

### ISSUE THREAD

**Issue by RyanGosden** [russellgoldenberg/scrollama#77]
We are using __scrollama__ to fix / unfix our navigation menu to the top of the page, once it reaches a step slightly further down from the top. 

It is working correctly most of the time, although it seems that on some occasions the event does not fire, especially if we scroll up and down fast. 

We are experiencing this on __Chrome Version 68.0.3440.75 (Official Build)  running on Ubuntu 16.04 (64-bit)__. (currently not tested on other browsers)

**Comment by SantoFejoDK** [comment]
Noticed this as well.

**Comment by russellgoldenberg** [comment]
Separate from this issue, I would suggest using position sticky for something like that.  [Full blog post here](https://pudding.cool/process/scrollytelling-sticky/).
