### ISSUE TITLE
Events misfiring on Android Chrome 71

### ISSUE THREAD

**Issue by zzzev** [russellgoldenberg/scrollama#81]
The scrollama events are not firing as expected (incorrect values, wrong step element) when running scrollama on a Pixel XL 2 w/ Android Chrome*. I discovered this in my own project, but it happens on the examples too; see [this screen recording](https://drive.google.com/file/d/1QoyZVjO0qHyZIS7dTCi7EDnq1MmUUTHw/view?usp=sharing) of the "progress" example. For the first half, I just scroll up and down, and you can see things jump around and report incorrect progress. Then, in the second half of the recording, I repeatedly reload the page, which shows it's not loading deterministically (it's pretty weird looking).

This also happens on the basic demo; it's just clearer to show what's going wrong on the progress one.

This does not happen on desktop, or in desktop Chrome's device emulation mode, or on an Android emulator, only on the actual device. It also does not happen in Firefox on the device, though the resizing of the steps is jumpy.

I would be more than happy to help debug this issue, let me know if I can provide any more useful information.

\* Version details:
Android Chrome version: 71.0.3578.99
OS version: Android 9; Pixel 2 XL Build/PQ1A.190105.004

**Comment by zzzev** [comment]
Correction: you **can** repro this on an emulator. You just need to make sure you have Chrome updated: the issue does not appear on the version of Android Chrome installed on the system images for the emulator (which I think was ~66), but it does appear when updated to the latest version (which is the same mentioned in the OP).

**Comment by zzzev** [comment]
I spent some more time digging deeper into this issue, and think I've narrowed it down to a bug in Chrome 71's handling of `rootMargin` on the `IntersectionObserver` when `devicePixelRatio != 1`. I've filed a bug against Chromium for [this issue here](https://bugs.chromium.org/p/chromium/issues/detail?id=923671), but I'm not sure what to expect in terms of resolution.

I have a pretty clear repro of the issue here: https://zzzev.github.io/intersectionobserver-bug-repro/index.html

Both sides work as expected when `devicePixelRatio == 1`. Only the left side works on Android Firefox (and Android Chrome 66), while only the right side works on Android Chrome 71.

All in all, unfortunate findings. You can probably work around this to some extent by using percent based lengths (which aren't going to be affected by devicePixelRatio), but for now it seems like the pixel-based ones are thoroughly busted on latest Android Chrome.

**Comment by Crashillo** [comment]
Same behaviour on Chrome 73, and DuckDuckGo browser (webkit, as well) for Android. But the @zzzev solution sounds quite easy. Any plan to implement it?

**Comment by JoBerkner** [comment]
@zzzev @Crashillo Any solution on this? It makes my story not really enjoyable on chrome mobile because the triggers are fired before my data visualization is actually visible in the viewport which means the user does not see animations etc. because he/she needs to read the associated text still...

**Comment by zzzev** [comment]
The [bug I filed with Chromium was merged into another bug that was marked fixed](https://bugs.chromium.org/p/chromium/issues/detail?id=966884), so this may be resolved; I haven't had a chance to check myself.

**Comment by nothaldir** [comment]
Hi,
I ran into the same problem on Chrome Android when developing an app using Intersection Oberserves with rootMargin.
I can confirm the issue was fixed and can actually be checked on Chrome Canary and Chrome Beta (Android). I hope it won't be too long before actually coming to Chrome Android.
