### ISSUE TITLE
Different offset for enter and  exit

### ISSUE THREAD

**Issue by davidhellmann** [russellgoldenberg/scrollama#84]
Is there a way to have on enter an `offset: 1` and on leave an `offset: 0`
Simple use case is I would add an `is-visible` class when it's enter the viewport and remove this class if its leave the viewport :)

Something like: `offset: [1, 0]` would be nice.

**Comment by hacknug** [comment]
@davidhellmann did you manage to solve this somehow?

**Comment by davidhellmann** [comment]
Not really :|

**Comment by jsunsawyer** [comment]
Looking for this functionality as well. My use case is to utilize Scrollama (which we're already using) to handle playing/pausing video elements as they scroll into view.

**Comment by alexsorinsky** [comment]
so, any progress for this feature ?
just have to use native Intersection Observer 'coz leak of this simple feature...

**Comment by russellgoldenberg** [comment]
yeah it exists in v3 - [checkout this thread](https://github.com/russellgoldenberg/scrollama/issues/122)
