### ISSUE TITLE
Progress only firing for part of div

### ISSUE THREAD

**Issue by paulmason** [russellgoldenberg/scrollama#86]
You can see here it's only printing to the console while scrolling the top ~38% of the banner div - https://monosnap.com/file/LTy2UHq4WCf8JlQ1WMadKHlY1VrGRH
I can set you up with a demo so you can inspect the css if you like?

Also Im intending to parallax that image, seems in theory like it should work fine using a `transform(translateY: response.progress)` Are there any limitations you're aware of? Thanks!

**Comment by cenda** [comment]
@paulmason same issue, have you solved the problem?

**Comment by russellgoldenberg** [comment]
Is this still an issue with the latest release? If so, please share code to reproduce and browser details.

**Comment by spectrachrome** [comment]
This is still an issue with the latest release, at least on the current macOS versions of Firefox, Chrome and Safari.
