### ISSUE TITLE
Offset trigger not working properly on Chrome mobile.

### ISSUE THREAD

**Issue by JoBerkner** [russellgoldenberg/scrollama#87]
I have the issue that my offset of 0.1 doesn't seem to work on mobile chrome browser (It does work as expected on desktop and Samsung Internet browser). On Chrome mobile it triggers earlier (before the dotted line for `debug: true` is reached). Anybody with same issues and a possible solution?

**Comment by bovas85** [comment]
I usually set up a different offset for mobile

**Comment by JoBerkner** [comment]
@bovas85: For my use case it is not necessary, because the trigger is called on exit from viewport (in my case when exiting `top: 10%`). My problem is that the event is not triggered at the assigned offset on Chrome mobile (however on Samsung Internet it works well)

**Comment by JoBerkner** [comment]
@russellgoldenberg I am not sure if it is only me, but also your [sample cases](https://russellgoldenberg.github.io/scrollama/basic/) are not working probably on chrome. The trigger is called somehow randomly and never at the debug line.

**Comment by russellgoldenberg** [comment]
Working as expected in the current release on android 9 moto g6 chrome 80. Still an issue?

**Comment by mtdmali** [comment]
FWIW I was having similar issues using Scrollama v2.2.3, where `onStepEnter` events were not firing as expected on my iPhone 12 using iOS 15.1.1.

Simply updating Scrollama to the latest v3.0.2 seems to have solved the problem, all the `onStepEnter` events are firing like normal for me now in both Chrome & Safari!

@russellgoldenberg
