### ISSUE TITLE
Warn user about offset value

### ISSUE THREAD

**Issue by ddazal** [russellgoldenberg/scrollama#88]
Hi, I've been reading the code just to know how this works and I encountered that the `offsetTrigger` function does not warn the user if the value of the offset is:

- lower than 0
- greater than 1
- not a number

The warnings should be something like: 
- `scrollama error: offset value is lower than 0. Fallbacks to 0`
- `scrollama error: offset value if greater than 1. Fallbacks to 1`
- `scrollama error: offset value is not a number. Fallbacks to 0`

I'm willing to submit a pull request if you think this is necessary. Great library BTW! :smile:

**Comment by russellgoldenberg** [comment]
good point. feel free to submit a PR if you are comfortable otherwise i can integrate at some point...
